name: Staging rollback

on:
  workflow_dispatch:
    inputs:
      release_name:
        description: 'Tag to rollback to'
        required: true

env:
  SSH_KEY: ${{ secrets.STAGE_SSH_PRIVATE_KEY }}
  SSH_PASSPHRASE: ${{ secrets.STAGE_SSH_PASSPHRASE }}
  BRANCH: main
  ADDONS_PATH: /opt
  APP_PATH: /opt/odoo/test_webseeds/
  STAGE_IP: "192.168.1.1"
  SSH_PORT: "22"

jobs:
  Deploy:
    runs-on: self-hosted
    steps:
      - name: Pull code
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.STAGE_IP }}
          username: root
          key: ${{ env.SSH_KEY }}
          passphrase: ${{ env.SSH_PASSPHRASE }}
          port: ${{ env.SSH_PORT }}
          script: |
            cd ${{ env.ADDONS_PATH }}
            git checkout ${{ env.BRANCH }} && git pull
            TAG=${{ github.event.inputs.release_name }}
            git checkout -b $TAG $TAG
            echo "Latest tag need to deploy is $TAG"
            chmod 777 webseeds_rma/static/src/img/*
            cd ${{ env.APP_PATH }} && docker-compose restart test